services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - backend_net

  rtsp_backend:
    build: .
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: daphne -b 0.0.0.0 -p 8000 rtsp_backend.asgi:application
    restart: always
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge
