services:
  - type: web
    name: rtsp-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: django-insecure-d^cf&dza8zcie&&30%4@^pfo#7+byc%!!gb^wki==tmr3b8669
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1
      - key: WS_BASE_URL
        value: ws://localhost:8000
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,http://example.com
